olanguage: csharp
solution: EscherAuth.sln
mono:
  - latest

sudo: false

addons:
  apt:
    packages:
      - nunit-console
      - mono-xbuild

script:
  - xbuild /p:Configuration=Release EscherAuth.sln
  - nunit-console ./EscherAuthTests/bin/Release/EscherAuthTests.dll

